### ISSUE TITLE
Merge and Squash Part 2 Example

### ISSUE THREAD

**Issue by xfrehner1** [xfrehner1/CS471WorkflowsHomeworkAssignment#12]
References user story #1

NOTE: the commits in the branch `task-6_squash_preferred_project_workflow` **DO NOT** reference task `#6`, and this is why this is the **preferred workflow** for the remaining sprints of the group project, and can be used for open-source or industry projects as well.

## TODO:
- [ ] Create a new PR having the **base** branch `master` and the **compare** branch `task-6_squash_preferred_project_workflow`
- [ ] Edit the description of the PR to reference this task
- [ ] In the PR, use the `Squash and merge` option to integrate the changes into `master` and the commit message should be `Closes #7 (#<ID_PR>)`, and **remove the extended description in the squashed commit, which lists the individual commits that are in the pull request**
- [ ] Use the GitHub interface to delete the branch of the PR after successfully integrating it into `master`
